import { normalizeWebsiteUrl } from "@/lib/data/intake/validation";
import type {
  Contact,
  ContactPathKind,
  ContactQualitySnapshot,
  ContactStatus,
  SourceReference,
} from "@/lib/domain";

const FREE_EMAIL_DOMAINS = new Set([
  "gmail.com",
  "googlemail.com",
  "yahoo.com",
  "hotmail.com",
  "outlook.com",
  "icloud.com",
  "aol.com",
  "proton.me",
  "protonmail.com",
]);

const PLATFORM_OR_SYSTEM_DOMAINS = [
  "wix.com",
  "wixsite.com",
  "squarespace.com",
  "weebly.com",
  "godaddy.com",
  "hubspot.com",
  "webflow.io",
  "zendesk.com",
  "freshdesk.com",
];

const ROLE_INBOX_LOCAL_PARTS = new Set([
  "info",
  "sales",
  "contact",
  "hello",
  "team",
  "office",
  "support",
  "service",
  "frontdesk",
  "reception",
  "appointments",
  "customerservice",
  "customercare",
]);

const JUNK_LOCAL_PART_PATTERNS = [
  /^no[\W_]?reply$/i,
  /^do[\W_]?not[\W_]?reply$/i,
  /^donotreply$/i,
  /^mailer[\W_]?daemon$/i,
  /^postmaster$/i,
  /^monitor(ing)?$/i,
  /^alerts?$/i,
  /^notifications?$/i,
  /^system$/i,
  /^admin(istrator)?$/i,
  /^wordpress$/i,
  /^webmaster$/i,
];

function dedupeStrings(values: Array<string | undefined>) {
  return Array.from(
    new Set(values.map((value) => value?.trim()).filter((value): value is string => Boolean(value))),
  );
}

function clampScore(score: number) {
  return Math.max(0, Math.min(100, Math.round(score)));
}

function normalizeEmail(email: string | undefined) {
  return email?.trim().toLowerCase();
}

function getEmailLocalPart(email: string | undefined) {
  return normalizeEmail(email)?.split("@")[0] ?? "";
}

function getEmailHost(email: string | undefined) {
  return normalizeEmail(email)?.split("@")[1]?.replace(/^www\./, "") ?? "";
}

function looksAutoGenerated(localPart: string) {
  return /(?:\d{4,}|[_-]\d{3,})/.test(localPart) || /^(contact|sales|info)[._-]?[0-9]{2,}$/i.test(localPart);
}

export function getCompanyHost(website: string | undefined) {
  const normalized = normalizeWebsiteUrl(website);

  if (!normalized) {
    return undefined;
  }

  return new URL(normalized).hostname.replace(/^www\./, "").toLowerCase();
}

export function isRoleInbox(email: string | undefined) {
  return ROLE_INBOX_LOCAL_PARTS.has(getEmailLocalPart(email));
}

export function isSameCompanyDomain(
  email: string | undefined,
  host: string | undefined,
) {
  if (!email || !host) {
    return false;
  }

  const emailHost = getEmailHost(email);

  return emailHost === host || emailHost.endsWith(`.${host}`) || host.endsWith(`.${emailHost}`);
}

export interface ContactPathAssessment {
  rankScore: number;
  qualityTier: ContactQualitySnapshot["qualityTier"];
  pathKind: ContactPathKind;
  campaignEligible: boolean;
  warnings: string[];
  selectionReasons: string[];
  status: ContactStatus;
  confidenceScore: number;
}

export interface RankedContactSelection {
  contact: Contact;
  selectionScore: number;
  selectionRank: number;
  isPrimary: boolean;
  selectionReasons: string[];
  demotionReasons: string[];
}

function getContactRankScore(contact: Contact) {
  return contact.quality?.rankScore ?? Math.round(contact.confidence.score * 100);
}

function getRoleSelectionBonus(contact: Contact) {
  switch (contact.role) {
    case "owner":
      return {
        score: 18,
        reason: "Role points to final vendor decision authority",
      };
    case "operator_owner":
      return {
        score: 16,
        reason: "Role points to hands-on operator decision authority",
      };
    case "general_manager":
      return {
        score: 12,
        reason: "Role points to day-to-day operating authority",
      };
    case "dealership_manager":
      return {
        score: 8,
        reason: "Role supports store-level routing and operational context",
      };
    case "sales_manager":
      return {
        score: 5,
        reason: "Role may influence follow-up and post-sale workflow decisions",
      };
    case "unknown":
      return {
        score: 0,
        reason: undefined,
      };
  }
}

function canBePrimaryContact(contact: Contact) {
  return (
    contact.status !== "invalid" &&
    contact.status !== "do_not_contact" &&
    Boolean(contact.email || contact.phone || contact.fullName)
  );
}

function assessContactForPrimarySelection(
  contact: Contact,
  preferredContactId: Contact["id"] | undefined,
) {
  let selectionScore = getContactRankScore(contact);
  const selectionReasons: string[] = [];
  const demotionReasons: string[] = [];
  const roleBonus = getRoleSelectionBonus(contact);

  if (contact.quality?.campaignEligible ?? contact.outreachReady) {
    selectionScore += 12;
    selectionReasons.push("Outreach path is ready for campaign use");
  }

  if (contact.status === "verified") {
    selectionScore += 10;
    selectionReasons.push("Contact is verified");
  } else if (contact.status === "candidate") {
    selectionScore += 3;
    selectionReasons.push("Contact is a live decision-maker hypothesis");
  } else if (contact.status === "invalid") {
    selectionScore -= 80;
    demotionReasons.push("Contact is marked invalid");
  } else if (contact.status === "do_not_contact") {
    selectionScore -= 120;
    demotionReasons.push("Contact is marked do not contact");
  }

  if (contact.email) {
    selectionScore += 8;
    selectionReasons.push("Direct email path is available");
  } else if (contact.phone) {
    selectionScore += 4;
    selectionReasons.push("Phone fallback is available");
  } else {
    demotionReasons.push("No direct outreach path is available yet");
  }

  if (contact.fullName) {
    selectionScore += 6;
    selectionReasons.push("Named person is attached to the record");
  } else if (contact.quality?.pathKind !== "role_inbox") {
    demotionReasons.push("Named decision-maker still needs verification");
  }

  if (contact.title) {
    selectionScore += 4;
    selectionReasons.push(`Title captured: ${contact.title}`);
  }

  if (contact.linkedinUrl) {
    selectionScore += 2;
    selectionReasons.push("LinkedIn profile is attached");
  }

  if (roleBonus.score > 0) {
    selectionScore += roleBonus.score;
  }

  if (roleBonus.reason) {
    selectionReasons.push(roleBonus.reason);
  }

  if (preferredContactId === contact.id || contact.isPrimary) {
    selectionScore += 6;
    selectionReasons.push("Current primary contact was preserved where reasonable");
  }

  if (contact.quality?.qualityTier === "weak") {
    selectionScore -= 8;
    demotionReasons.push("Current contact path is still weak");
  }

  if (contact.quality?.qualityTier === "junk") {
    selectionScore -= 24;
    demotionReasons.push("Current contact path looks unusable for outreach");
  }

  if (contact.quality?.warnings[0]) {
    demotionReasons.push(contact.quality.warnings[0]);
  }

  return {
    contact,
    selectionScore: Math.round(selectionScore),
    selectionReasons: dedupeStrings(selectionReasons),
    demotionReasons: dedupeStrings(demotionReasons),
  };
}

export function rankContactsForPrimarySelection(
  contacts: readonly Contact[],
  options?: {
    preferredContactId?: Contact["id"];
  },
): RankedContactSelection[] {
  const assessed = contacts.map((contact) =>
    assessContactForPrimarySelection(contact, options?.preferredContactId),
  );
  const ordered = [...assessed].sort((left, right) => {
    if (right.selectionScore !== left.selectionScore) {
      return right.selectionScore - left.selectionScore;
    }

    if (getContactRankScore(right.contact) !== getContactRankScore(left.contact)) {
      return getContactRankScore(right.contact) - getContactRankScore(left.contact);
    }

    if (
      Number(right.contact.status === "verified") !==
      Number(left.contact.status === "verified")
    ) {
      return (
        Number(right.contact.status === "verified") -
        Number(left.contact.status === "verified")
      );
    }

    if (Number(Boolean(right.contact.email)) !== Number(Boolean(left.contact.email))) {
      return Number(Boolean(right.contact.email)) - Number(Boolean(left.contact.email));
    }

    if (
      Number(Boolean(right.contact.fullName)) !== Number(Boolean(left.contact.fullName))
    ) {
      return (
        Number(Boolean(right.contact.fullName)) -
        Number(Boolean(left.contact.fullName))
      );
    }

    if (Number(right.contact.isPrimary) !== Number(left.contact.isPrimary)) {
      return Number(right.contact.isPrimary) - Number(left.contact.isPrimary);
    }

    return left.contact.createdAt.localeCompare(right.contact.createdAt);
  });
  const primary = ordered.find((candidate) => canBePrimaryContact(candidate.contact));

  return ordered.map((candidate, index) => {
    const isPrimary = candidate.contact.id === primary?.contact.id;
    const primaryLabel =
      primary?.contact.fullName ??
      primary?.contact.email ??
      primary?.contact.phone ??
      "another contact";

    return {
      ...candidate,
      selectionRank: index + 1,
      isPrimary,
      selectionReasons: dedupeStrings([
        ...candidate.selectionReasons,
        isPrimary ? "Selected as the primary outreach contact" : undefined,
      ]),
      demotionReasons: dedupeStrings([
        ...candidate.demotionReasons,
        !isPrimary && primary
          ? `${primaryLabel} ranked higher for primary outreach`
          : undefined,
      ]),
    };
  });
}

export function selectPrimaryContact(
  contacts: readonly Contact[],
  options?: {
    preferredContactId?: Contact["id"];
  },
) {
  return rankContactsForPrimarySelection(contacts, options).find(
    (selection) => selection.isPrimary,
  )?.contact;
}

export function applyPrimaryContactSelection(params: {
  contacts: readonly Contact[];
  preferredContactId?: Contact["id"];
  now: string;
}) {
  const rankedContacts = rankContactsForPrimarySelection(params.contacts, {
    preferredContactId: params.preferredContactId,
  });
  const updatedContacts = rankedContacts.map((selection) => ({
    ...selection.contact,
    isPrimary: selection.isPrimary,
    confidence: {
      ...selection.contact.confidence,
      signals: dedupeStrings([
        ...selection.contact.confidence.signals,
        ...selection.selectionReasons,
      ]),
    },
    quality: selection.contact.quality
      ? {
          ...selection.contact.quality,
          selectionScore: selection.selectionScore,
          selectionRank: selection.selectionRank,
          selectionReasons: dedupeStrings([
            ...selection.contact.quality.selectionReasons,
            ...selection.selectionReasons,
          ]),
          demotionReasons: dedupeStrings([
            ...selection.contact.quality.demotionReasons,
            ...selection.demotionReasons,
          ]),
          lastAssessedAt: params.now,
        }
      : undefined,
    updatedAt: params.now,
  }));

  return {
    contacts: updatedContacts,
    primaryContact: updatedContacts.find((contact) => contact.isPrimary),
  };
}

export function assessContactPath(params: {
  email?: string;
  phone?: string;
  fullName?: string;
  title?: string;
  companyHost?: string;
  source?: SourceReference;
  hasWebsiteEvidence?: boolean;
  preferCurrentPrimary?: boolean;
}): ContactPathAssessment {
  const email = normalizeEmail(params.email);
  const localPart = getEmailLocalPart(email);
  const emailHost = getEmailHost(email);
  const sameDomain = isSameCompanyDomain(email, params.companyHost);
  const roleInbox = isRoleInbox(email);
  const usesFreeInbox = FREE_EMAIL_DOMAINS.has(emailHost);
  const usesPlatformDomain = PLATFORM_OR_SYSTEM_DOMAINS.some(
    (domain) => emailHost === domain || emailHost.endsWith(`.${domain}`),
  );
  const looksSystemOwned = JUNK_LOCAL_PART_PATTERNS.some((pattern) => pattern.test(localPart));
  const hasNamedPerson = Boolean(params.fullName && !roleInbox);
  const hasTitle = Boolean(params.title);
  const warnings: string[] = [];
  const selectionReasons: string[] = [];
  let score = 0;

  if (email) {
    score += 16;
    selectionReasons.push(`Email path available: ${email}`);
  }

  if (sameDomain) {
    score += 42;
    selectionReasons.push("Email matches the company website domain");
  } else if (email && params.companyHost) {
    score -= 26;
    warnings.push("Email domain does not match the company website");
  }

  if (hasNamedPerson && email) {
    score += 26;
    selectionReasons.push("Named person is attached to the contact path");
  } else if (params.fullName) {
    score += 10;
    selectionReasons.push("A likely contact name was found");
  }

  if (roleInbox && email) {
    score += sameDomain ? 18 : 6;
    selectionReasons.push("Role inbox gives a usable business contact path");
  } else if (email && sameDomain) {
    score += 14;
    selectionReasons.push("Email looks like a relevant business inbox on the company domain");
  }

  if (params.phone) {
    score += email ? 4 : 24;
    selectionReasons.push(
      email
        ? "Phone coverage is available as a supporting fallback"
        : "Phone fallback is available when no email is present",
    );
  }

  if (hasTitle) {
    score += 6;
    selectionReasons.push(`Title captured: ${params.title}`);
  }

  if (params.hasWebsiteEvidence) {
    score += 6;
    selectionReasons.push("Website evidence supports this contact path");
  }

  if (params.preferCurrentPrimary) {
    score += 4;
    selectionReasons.push("Existing primary contact was preserved where possible");
  }

  if (usesFreeInbox) {
    score -= 26;
    warnings.push("Free-email domain needs manual review before outreach");
  }

  if (usesPlatformDomain) {
    score -= 32;
    warnings.push("Address appears to belong to a platform or site-builder domain");
  }

  if (looksSystemOwned) {
    score -= 46;
    warnings.push("Address looks like a no-reply or system-owned inbox");
  }

  if (looksAutoGenerated(localPart)) {
    score -= 18;
    warnings.push("Address looks auto-generated and may not be a real outreach target");
  }

  if (!email && !params.phone) {
    warnings.push("No direct outreach path is attached yet");
  }

  const rankScore = clampScore(score);
  const pathKind: ContactPathKind = email
    ? hasNamedPerson && !roleInbox
      ? "named_email"
      : roleInbox
        ? "role_inbox"
        : "general_business_email"
    : params.phone
      ? "phone_only"
      : "unknown";
  const qualityTier: ContactQualitySnapshot["qualityTier"] =
    rankScore >= 82 && pathKind === "named_email"
      ? "strong"
      : rankScore >= 64 && email && sameDomain && !looksSystemOwned && !usesPlatformDomain
        ? "usable"
        : rankScore >= 38 && (email || params.phone)
          ? "weak"
          : "junk";
  const campaignEligible =
    Boolean(email) &&
    sameDomain &&
    !usesPlatformDomain &&
    !looksSystemOwned &&
    (qualityTier === "strong" || qualityTier === "usable");
  const status: ContactStatus =
    qualityTier === "junk"
      ? "invalid"
      : campaignEligible
        ? "verified"
        : "candidate";

  if (!campaignEligible && email) {
    warnings.push("This path should not auto-enroll into outreach without review");
  }

  if (campaignEligible && !hasNamedPerson) {
    warnings.push("A named person is still missing, so outreach confidence stays lower");
  }

  return {
    rankScore,
    qualityTier,
    pathKind,
    campaignEligible,
    warnings: dedupeStrings(warnings),
    selectionReasons: dedupeStrings(selectionReasons),
    status,
    confidenceScore:
      qualityTier === "strong"
        ? 0.92
        : qualityTier === "usable"
          ? 0.78
          : qualityTier === "weak"
            ? 0.54
            : 0.28,
  };
}

export function buildContactQualitySnapshot(
  assessment: Pick<
    ContactPathAssessment,
    | "rankScore"
    | "qualityTier"
    | "pathKind"
    | "campaignEligible"
    | "warnings"
    | "selectionReasons"
  >,
  now: string,
  overrides?: Partial<
    Pick<ContactQualitySnapshot, "selectionReasons" | "demotionReasons" | "warnings">
  >,
): ContactQualitySnapshot {
  return {
    rankScore: assessment.rankScore,
    qualityTier: assessment.qualityTier,
    pathKind: assessment.pathKind,
    campaignEligible: assessment.campaignEligible,
    warnings: dedupeStrings([...(assessment.warnings ?? []), ...(overrides?.warnings ?? [])]),
    selectionReasons: dedupeStrings([
      ...(assessment.selectionReasons ?? []),
      ...(overrides?.selectionReasons ?? []),
    ]),
    demotionReasons: dedupeStrings(overrides?.demotionReasons ?? []),
    lastAssessedAt: now,
  };
}

export function getContactSourceLabel(contact: Pick<Contact, "source">) {
  return `${contact.source.label ?? contact.source.provider} (${contact.source.kind})`;
}
