export type SchemaFieldType =
  | "id"
  | "string"
  | "text"
  | "number"
  | "boolean"
  | "datetime"
  | "enum"
  | "json";

export interface SchemaFieldDefinition {
  name: string;
  type: SchemaFieldType;
  nullable?: boolean;
  list?: boolean;
  references?: string;
  description?: string;
}

export interface EntitySchemaDefinition {
  entity: string;
  table: string;
  primaryKey: string;
  fields: SchemaFieldDefinition[];
}

export const entitySchemas: EntitySchemaDefinition[] = [
  {
    entity: "Company",
    table: "companies",
    primaryKey: "id",
    fields: [
      { name: "id", type: "id" },
      { name: "name", type: "string" },
      { name: "legalName", type: "string", nullable: true },
      { name: "industryKey", type: "string" },
      { name: "subindustry", type: "string", nullable: true },
      { name: "icpProfileId", type: "id", references: "icp_profiles.id" },
      { name: "status", type: "enum" },
      { name: "priorityTier", type: "enum" },
      { name: "isIndependent", type: "boolean" },
      { name: "location", type: "json" },
      { name: "presence", type: "json" },
      { name: "monthlyCarsSoldRange", type: "json", nullable: true },
      { name: "likelyOperatorAgeRange", type: "json", nullable: true },
      { name: "softwareToolCountEstimate", type: "number", nullable: true },
      { name: "buyingStage", type: "enum" },
      { name: "painSignals", type: "string", list: true },
      { name: "disqualifierSignals", type: "string", list: true },
      { name: "notes", type: "text", list: true },
      { name: "recommendedOfferIds", type: "id", list: true, references: "offers.id" },
      { name: "primaryContactId", type: "id", nullable: true, references: "contacts.id" },
      { name: "activeCampaignIds", type: "id", list: true, references: "campaigns.id" },
      { name: "appointmentIds", type: "id", list: true, references: "appointments.id" },
      { name: "scoring", type: "json" },
      { name: "enrichment", type: "json", nullable: true },
      { name: "source", type: "json" },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
    ],
  },
  {
    entity: "Contact",
    table: "contacts",
    primaryKey: "id",
    fields: [
      { name: "id", type: "id" },
      { name: "companyId", type: "id", references: "companies.id" },
      { name: "fullName", type: "string", nullable: true },
      { name: "title", type: "string", nullable: true },
      { name: "role", type: "enum" },
      { name: "email", type: "string", nullable: true },
      { name: "phone", type: "string", nullable: true },
      { name: "linkedinUrl", type: "string", nullable: true },
      { name: "sourceKind", type: "enum" },
      { name: "status", type: "enum" },
      { name: "isPrimary", type: "boolean" },
      { name: "outreachReady", type: "boolean" },
      { name: "confidence", type: "json" },
      { name: "quality", type: "json", nullable: true },
      { name: "notes", type: "text", list: true },
      { name: "source", type: "json" },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
    ],
  },
  {
    entity: "Offer",
    table: "offers",
    primaryKey: "id",
    fields: [
      { name: "id", type: "id" },
      { name: "name", type: "string" },
      { name: "category", type: "enum" },
      { name: "description", type: "text" },
      { name: "problemSolved", type: "text" },
      { name: "bestFitSummary", type: "text" },
      { name: "fitSignals", type: "text", list: true },
      { name: "firstOutreachAngle", type: "text" },
      { name: "primaryCta", type: "text" },
      { name: "timing", type: "enum" },
      { name: "isPrimaryFrontDoor", type: "boolean" },
      { name: "pricing", type: "json", nullable: true },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
    ],
  },
  {
    entity: "Campaign",
    table: "campaigns",
    primaryKey: "id",
    fields: [
      { name: "id", type: "id" },
      { name: "name", type: "string" },
      { name: "description", type: "text" },
      { name: "status", type: "enum" },
      { name: "offerId", type: "id", references: "offers.id" },
      { name: "primaryIcpProfileId", type: "id", references: "icp_profiles.id" },
      { name: "targetTier", type: "enum" },
      { name: "sequenceId", type: "id", references: "sequences.id" },
      { name: "channel", type: "enum" },
      { name: "objective", type: "text" },
      { name: "goalMetric", type: "string" },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
    ],
  },
  {
    entity: "Sequence",
    table: "sequences",
    primaryKey: "id",
    fields: [
      { name: "id", type: "id" },
      { name: "name", type: "string" },
      { name: "lineageKey", type: "string" },
      { name: "version", type: "number" },
      { name: "offerId", type: "id", references: "offers.id" },
      { name: "status", type: "enum" },
      { name: "targetTier", type: "enum" },
      { name: "audienceSummary", type: "text" },
      { name: "goal", type: "text" },
      { name: "steps", type: "json" },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
    ],
  },
  {
    entity: "Enrollment",
    table: "enrollments",
    primaryKey: "id",
    fields: [
      { name: "id", type: "id" },
      { name: "companyId", type: "id", references: "companies.id" },
      { name: "contactId", type: "id", references: "contacts.id" },
      { name: "campaignId", type: "id", references: "campaigns.id" },
      { name: "sequenceId", type: "id", references: "sequences.id" },
      { name: "offerId", type: "id", references: "offers.id" },
      { name: "priorityTier", type: "enum" },
      { name: "state", type: "enum" },
      { name: "currentStepIndex", type: "number" },
      { name: "enteredSequenceAt", type: "datetime" },
      { name: "nextActionAt", type: "datetime", nullable: true },
      { name: "lastContactedAt", type: "datetime", nullable: true },
      { name: "lastReplyId", type: "id", nullable: true, references: "replies.id" },
      { name: "appointmentId", type: "id", nullable: true, references: "appointments.id" },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
    ],
  },
  {
    entity: "Reply",
    table: "replies",
    primaryKey: "id",
    fields: [
      { name: "id", type: "id" },
      { name: "enrollmentId", type: "id", references: "enrollments.id" },
      { name: "companyId", type: "id", references: "companies.id" },
      { name: "contactId", type: "id", references: "contacts.id" },
      { name: "campaignId", type: "id", references: "campaigns.id" },
      { name: "offerId", type: "id", references: "offers.id" },
      { name: "channel", type: "enum" },
      { name: "classification", type: "enum" },
      { name: "sentiment", type: "enum", nullable: true },
      { name: "snippet", type: "text" },
      { name: "bodyText", type: "text" },
      { name: "receivedAt", type: "datetime" },
      { name: "requiresHumanReview", type: "boolean" },
      { name: "indicatesBookingIntent", type: "boolean" },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
    ],
  },
  {
    entity: "Appointment",
    table: "appointments",
    primaryKey: "id",
    fields: [
      { name: "id", type: "id" },
      { name: "companyId", type: "id", references: "companies.id" },
      { name: "contactId", type: "id", references: "contacts.id" },
      { name: "campaignId", type: "id", references: "campaigns.id" },
      { name: "enrollmentId", type: "id", references: "enrollments.id" },
      { name: "replyId", type: "id", references: "replies.id" },
      { name: "status", type: "enum" },
      { name: "confirmationStatus", type: "enum" },
      { name: "bookedAt", type: "datetime" },
      { name: "scheduledFor", type: "datetime" },
      { name: "timezone", type: "string" },
      { name: "notes", type: "text", nullable: true },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
    ],
  },
  {
    entity: "Experiment",
    table: "experiments",
    primaryKey: "id",
    fields: [
      { name: "id", type: "id" },
      { name: "name", type: "string" },
      { name: "hypothesis", type: "text" },
      { name: "status", type: "enum" },
      { name: "targetEntityType", type: "enum" },
      { name: "targetEntityId", type: "string", nullable: true },
      { name: "primaryMetric", type: "string" },
      { name: "variantKeys", type: "string", list: true },
      { name: "winningVariantKey", type: "string", nullable: true },
      { name: "startedAt", type: "datetime", nullable: true },
      { name: "endedAt", type: "datetime", nullable: true },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
    ],
  },
  {
    entity: "Insight",
    table: "insights",
    primaryKey: "id",
    fields: [
      { name: "id", type: "id" },
      { name: "type", type: "enum" },
      { name: "title", type: "string" },
      { name: "summary", type: "text" },
      { name: "confidence", type: "number" },
      { name: "sourceEntityType", type: "enum" },
      { name: "sourceEntityId", type: "string", nullable: true },
      { name: "tags", type: "string", list: true },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
    ],
  },
  {
    entity: "MemoryEntry",
    table: "memory_entries",
    primaryKey: "id",
    fields: [
      { name: "id", type: "id" },
      { name: "kind", type: "enum" },
      { name: "title", type: "string" },
      { name: "summary", type: "text" },
      { name: "relatedEntityType", type: "enum", nullable: true },
      { name: "relatedEntityId", type: "string", nullable: true },
      { name: "tags", type: "string", list: true },
      { name: "lastObservedAt", type: "datetime", nullable: true },
      { name: "createdAt", type: "datetime" },
      { name: "updatedAt", type: "datetime" },
    ],
  },
  {
    entity: "IcpProfile",
    table: "icp_profiles",
    primaryKey: "id",
    fields: [
      { name: "id", type: "id" },
      { name: "name", type: "string" },
      { name: "market", type: "string" },
      { name: "summary", type: "text" },
      { name: "monthlyCarsSoldRange", type: "json" },
      { name: "ageRange", type: "json" },
      { name: "googleRatingRange", type: "json" },
      { name: "reviewCountRange", type: "json" },
      { name: "websiteRequired", type: "boolean" },
      { name: "claimedGoogleBusinessProfileRequired", type: "boolean" },
      { name: "softwareToolCountMin", type: "number" },
      { name: "qualificationSignals", type: "text", list: true },
      { name: "disqualifiers", type: "text", list: true },
      { name: "likelyPains", type: "text", list: true },
      { name: "likelyObjections", type: "text", list: true },
      { name: "proofAngles", type: "text", list: true },
      { name: "decisionMakerHypotheses", type: "string", list: true },
      { name: "channelNotes", type: "text", list: true },
    ],
  },
];
